Repository fecgov/openFEC, pull requests merged in 2018-11, with the labels that each got.

#3471 refactor ofec_filings_all_mv to remove redundent RFAI rows
  data/migrations/V0117__update_ofec_filings_all_mv_rm_redundent_RFAI_data.sql
Labels: plz-review

#3473 Update sale or use link in open api
  webservices/docs.py
Labels: plz-review

#3472 Add contributor committee type filter to sched_a end point.
  tests/test_itemized.py
  webservices/args.py
  webservices/common/models/itemized.py
  webservices/resources/sched_a.py
Labels: plz-review

#3477 [MERGE WITH GIT FLOW] Add fallback zero values for Form 3 cash-on-hand
  webservices/schemas.py
Labels: Before release, Hotfix, plz-review

#3475 Add ‘count’ col to ScheduleABySizeCandidateView and ScheduleAByStateCandidateView
  tests/test_aggregates.py
  webservices/common/models/aggregates.py
  webservices/docs.py
  webservices/resources/candidate_aggregates.py
  webservices/schemas.py
Labels: plz-review

#3465 Add handling for include/exclude AO citations
  tests/test_ao_citations.py
  webservices/legal_docs/advisory_opinions.py
Labels: plz-review

#3474 Add optional parameter to sort nulls last
  tests/test_candidates.py
  tests/test_itemized.py
  webservices/args.py
  webservices/sorting.py
  webservices/utils.py
Labels: Before release, High priority, plz-review

#3483 Show history for first-time, future-cycle house candidates
  tests/test_candidates.py
  webservices/resources/candidates.py
Labels: plz-review

#3485 [MERGE WITH GIT FLOW] Show 2020 house candidate history
  tests/test_candidates.py
  webservices/resources/candidates.py
Labels: Hotfix

#3481 Switch to new schedule B aggrgeate tables with memo totals
  tests/factories.py
  tests/test_aggregates.py
  webservices/common/models/aggregates.py
  webservices/docs.py
  webservices/resources/aggregates.py
  webservices/schemas.py
Labels: plz-review

#3491 Automate elasticsearch backups
  manage.py
  webservices/legal_docs/__init__.py
  webservices/legal_docs/index_management.py
  webservices/tasks/__init__.py
  webservices/tasks/download.py
  webservices/tasks/legal_docs.py
Labels: plz-review

#3494 Disable sort_nulls_last for Sch A and B
  tests/test_itemized.py
  webservices/args.py
  webservices/resources/sched_a.py
  webservices/resources/sched_b.py
Labels: Before release, plz-review

#3508 Fix elasticsearch backup logic
  manage.py
  webservices/legal_docs/__init__.py
  webservices/legal_docs/index_management.py
  webservices/tasks/download.py
  webservices/tasks/legal_docs.py
  webservices/tasks/refresh.py
Labels: Before release, plz-review

#3512 Rename 'contributor_committee_type' to 'recipient_committee_type'
  tests/test_itemized.py
  webservices/args.py
  webservices/common/models/itemized.py
  webservices/resources/sched_a.py
Labels: plz-review

#3517 [MERGE WITH GIT FLOW] Update disposition data to filter for case_id
  webservices/legal_docs/current_cases.py
Labels: Hotfix
