Repository fecgov/openFEC, pull requests merged in 2018-07, with the labels that each got.

#3255 Remove the joint fundraisers inflating money from totals
  tests/test_elections.py
  webservices/resources/elections.py
Labels: plz-review

#3225 Remove 'won' from /elections/
  data/migrations/V0092__drop_ofec_election_result_mv.sql
  manage.py
  tests/factories.py
  tests/test_elections.py
  tests/test_utils.py
  webservices/common/models/elections.py
  webservices/resources/elections.py
  webservices/schemas.py
Labels: plz-review

#3269 Allow more complex parsing of AO citations
  tests/test_advisory_opinions.py
  webservices/legal_docs/advisory_opinions.py
Labels: plz-review

#3077 Updating with pre-release testing
  CONTRIBUTING.md
Labels: plz-review

#3203 [V0093] create operations log endpoint
  data/migrations/V0093__operations_log_view.sql
  tests/factories.py
  tests/test_operation_logs.py
  webservices/args.py
  webservices/common/models/__init__.py
  webservices/common/models/operations_log.py
  webservices/docs.py
  webservices/resources/operations_log.py
  webservices/rest.py
  webservices/schemas.py
Labels: Before release, plz-review

#3287 update migration file for permission problem
  data/migrations/V0096__drop_ofec_sched_a_objects.sql
Labels: plz-review

#3292 [WIP]Refactor elections endpoint to handle candidate finance totals export function
  tests/test_downloads.py
  tests/test_elections.py
  tests/test_utils.py
  webservices/resources/elections.py
  webservices/schemas.py
Labels: plz-review

#3298 Create itemized sched_e related tables and transfer data from fecp to postgresql database in cloud
  data/migrations/V0097__add_ofec_sched_e_mv.sql
  manage.py
  webservices/flow.py
Labels: plz-review

#3303 Fix elections endpoint to handle per_page=0
  webservices/resources/elections.py
Labels: plz-review

#3305 Update hotfix instructions in README
  README.md
Labels: plz-review

#3264 [WIP]Enable zipcode search for foreign zipcodes, and remove input of 5-digits restricition
  tests/test_itemized.py
  webservices/docs.py
  webservices/resources/sched_a.py
Labels: plz-review

#3315 [MERGE WITH GIT FLOW] Hotfix: Revert elasticsearch connection settings to the defaults
  webservices/utils.py
Labels: Hotfix, plz-review
