Repository fecgov/openFEC, pull requests merged in 2018-06, with the labels that each got.

#3169 Feature/switch sched a
  data/migrations/V0082__add_indexes_on_fec_fitem_sched_a_tables.sql
  tests/test_integration.py
  webservices/common/models/itemized.py
Labels: plz-review

#3178 Connect to Redis using URI parameter
  webservices/tasks/__init__.py
Labels: plz-review

#3194 Fix join on state for ofec_sched_a_aggregate_state_recipient_totals_mv
  data/migrations/V0083__fix_ofec_sched_a_aggregate_state_recipient_totals_mv.sql
Labels: plz-review

#3205 add table entity_chart
  data/migrations/V0084__add_table_entity_chart.sql
Labels: plz-review

#3198 Fix totals for off-year special candidates on /candidates/totals endpoint
  data/migrations/V0085__fix_ofec_candidate_totals_mv.sql
  manage.py
  tests/factories.py
  tests/test_aggregates.py
  tests/test_committees.py
  webservices/common/models/candidates.py
  webservices/flow.py
  webservices/resources/candidate_aggregates.py
Labels: Bug, High priority, plz-review

#3216 Feature/periodic refresh ao
  webservices/tasks/__init__.py
  webservices/tasks/cache_request.py
  webservices/tasks/json_response.py
  webservices/tasks/legal_docs.py
  webservices/tasks/refresh.py
  webservices/tasks/response_exception.py
  webservices/tasks/utils.py
Labels: plz-review

#3223 Update Flyway to v. 5.1.3
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
Labels: plz-review

#3231 Add committee_designation filter into audit-case endpoint
  webservices/args.py
Labels: plz-review

#3228 flyway badge addition
  README.md
Labels: Before release, plz-review

#3241 Renamed weekly reload AO task to match what's in schedule
  webservices/tasks/__init__.py
Labels: plz-review

#3245 Add /committee/<ID>/totals/ to API docs
  webservices/rest.py
Labels: plz-review

#3219 [V0086] Fix candidate totals for future elections
  data/migrations/V0086__add_future_ofec_candidate_totals_mv.sql
  manage.py
  tests/factories.py
  tests/test_aggregates.py
  tests/test_utils.py
  webservices/common/models/candidates.py
  webservices/flow.py
  webservices/resources/candidate_aggregates.py
  webservices/utils.py
Labels: Bug, plz-review
