Repository fecgov/openFEC, pull requests merged in 2019-09, with the labels that each got.

#3935 Fix inconsistent totals derived from misfiled F3* data
  data/migrations/V0159__ofec_candidate_totals_mv_include_all_F3_F3P_F3X_exclude_non_candidate_cmtes.sql
  data/migrations/V0160__ofec_totals_house_senate_mv_include_all_F3_F3P_F3X_exclude_non_H_S_candidate_cmtes.sql
Labels: Please review

#3958 [MERGE WITH GIT FLOW] Fix candidate 404
  tests/test_candidates.py
  webservices/resources/candidates.py
Labels: Hotfix, Please review

#3959 drop unused fec vsum sched tables, correct views with columns of data type unknown, switch MV definition to use base tables
  data/migrations/V0161__ofec_communication_cost_mv_replace_source.sql
  data/migrations/V0162__drop_fec_vsum_sched_vws.sql
  data/migrations/V0163__ofec_reports_ie_only_mv.sql
  data/migrations/V0164__correct_views_with_column_data_type_unknown.sql
  webservices/flow.py
Labels: Please review

#3972 Add ofec_sched_a_agg_state_mv to solve the slowness of ScheduleAByStateCandidate
  data/migrations/V0165__ofec_sched_a_agg_state_mv.sql
  manage.py
  webservices/flow.py
Labels: Please review

#3974 Add ofec_sched_a_agg_state_mv to solve the slowness of ScheduleAByStateCandidate
  data/migrations/V0165__ofec_sched_a_agg_state_mv.sql
Labels: Please review

#3973 Bring "Schedule A by state" speed improvements into the release
  data/migrations/V0165__ofec_sched_a_agg_state_mv.sql
  manage.py
  webservices/flow.py
Labels: Before release
