Repository fecgov/openFEC, pull requests merged in 2019-04, with the labels that each got.

#3658 OPENFEC - Add snyk links
  README.md
Labels: plz-review

#3674 update sched_a.py and sched_b.py and remove two year restriction.
  tests/test_itemized.py
  webservices/args.py
  webservices/config.py
  webservices/resources/sched_a.py
  webservices/resources/sched_b.py
Labels: plz-review

#3690 [MERGE WITH GIT FLOW] Hotfix: Temporarily block ip
  webservices/rest.py
Labels: Hotfix, plz-review

#3693 pin requirements for kombu 4.5.0
  requirements.txt
Labels: plz-review

#3676 Update Flyway to version 5.2.4
  .circleci/config.yml
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
Labels: Before release, plz-review

#3694 Fix incorrect totals for C00508416 (FRIENDS OF JOHN DELANEY) on committee profile page
  data/migrations/V0127__ofec_committee_totals_per_cycle_vw.sql
  tests/factories.py
  tests/test_totals.py
  webservices/common/models/totals.py
  webservices/resources/totals.py
  webservices/schemas.py
Labels: plz-review

#3687 candidate totals by party by office
  data/migrations/V0128__cand_totals_add_columns.sql
  endpoints_walk.py
  tests/test_aggregates.py
  webservices/args.py
  webservices/common/models/candidates.py
  webservices/docs.py
  webservices/resources/candidate_aggregates.py
  webservices/rest.py
  webservices/schemas.py
Labels: plz-review

#3695 Limit access to /downloads/ to one API key
  webservices/rest.py
Labels: Before release, plz-review

#3715 add fec_fitem_sched_a_2019_2020 and fec_fitem_sched_b_2019_2020 tables
  data/migrations/V0129__add_fec_fitem_sched_ab_2019_2020.sql
Labels: plz-review

#3682 add sort args to /schedule/schedule_d/{sub_id}/ endpoint
  tests/factories.py
  tests/test_sched_d.py
  webservices/common/models/itemized.py
  webservices/resources/sched_d.py
Labels: plz-review

#3714 Fix schedule_c endpoints incurred date filter not work
  tests/factories.py
  tests/test_sched_c.py
  webservices/args.py
  webservices/common/models/itemized.py
  webservices/docs.py
  webservices/resources/sched_c.py
Labels: plz-review

#3710 Fix search by analyst title and email
  tests/test_filing_resources.py
  webservices/common/models/rad_analyst.py
  webservices/resources/rad_analyst.py
Labels: plz-review

#3725 [MERGE WITH GIT FLOW] Hotfix: Limit large Schedule A queries
  tests/test_itemized.py
  webservices/resources/sched_a.py
Labels: Hotfix

#3726 [Do not merge before PR#3688 due to migration number]Fix bernie sanders totals incorrect
  data/migrations/V0131__ofec_cand_cmte_linkage_mv_add_column.sql
  data/migrations/V0132__ofec_cand_totals_mv_update.sql
  tests/test_elections.py
  tests/test_utils.py
  webservices/common/models/links.py
  webservices/resources/elections.py
Labels: plz-review
