Repository fecgov/openFEC, pull requests merged in 2019-12, with the labels that each got.

#4095 Feature/3834 tsvector sa7
  data/migrations/V0174__add_tsvector_trigger_to_sa7.sql
  tests/integration/test_tsvector_generation.py
Labels: Bug, Work: Back-end

#4099 [Merge after 4095 due to migration file order] Fix candidate_search column to return all possible results
  data/migrations/V0175__update_real_efile_se_f57_vw_cand_fulltxt_tsvector_column.sql
Labels: Please review

#4110 Feature/4109 swagger is not in package file
  .circleci/config.yml
  README.md
  package-lock.json
  package.json
Labels: Please review

#4122 Feature/4073 update flask dependencies
  requirements.txt
Labels: dependencies

#4124 Update endpoints_walk.
  endpoints_walk.py
Labels: Please review

#4125 Update GPO statute link format
  tests/data/archived_mur_bad_pdf_doc.json
  tests/data/archived_mur_doc.json
  tests/data/archived_mur_multi_part_doc.json
  tests/integration/test_current_cases.py
  tests/test_load_legal_docs.py
  tests/test_map_citations_murs.py
  tests/test_parse_mur_citations.py
  webservices/legal_docs/current_cases.py
  webservices/legal_docs/load_legal_docs.py
  webservices/legal_docs/responses.py
Labels: Before release, Please review

#4127 Remove deprecated endpoints
  tests/test_aggregates_by_committee_id.py
  webservices/args.py
  webservices/resources/aggregates_by_committeeID.py
  webservices/rest.py
Labels: Please review

#4131 Update raw efile docs to reflect 4 months of data instead of 2 years
  webservices/docs.py
Labels: PI board, Work: Back-end, Work: Content
