Repository fecgov/openFEC, pull requests merged in 2019-03, with the labels that each got.

#3596 update ofec_candidate_history_mv to fix cand_inactive value
  data/migrations/V0124__ofec_candidate_history_mv_update_cand_inactive.sql
Labels: plz-review

#3600 Increase API timeout to 300
  bin/run.sh
Labels: plz-review

#3605 Upgrade redis to version 3.2.0
  requirements.txt
Labels: Before release, plz-review

#3606 Update OS stack to cflinuxfs3
  manifests/manifest_api_dev.yml
  manifests/manifest_api_prod.yml
  manifests/manifest_api_stage.yml
  manifests/manifest_celery_beat_dev.yml
  manifests/manifest_celery_beat_prod.yml
  manifests/manifest_celery_beat_stage.yml
  manifests/manifest_celery_worker_dev.yml
  manifests/manifest_celery_worker_prod.yml
  manifests/manifest_celery_worker_stage.yml
  manifests/manifest_task_dev.yml.template
  manifests/manifest_task_prod.yml.template
  manifests/manifest_task_stage.yml.template
  requirements.txt
Labels: plz-review

#3615 Temporarily remove prance[osv] and swagger validation
  requirements.txt
  tests/test_swagger.py
Labels: plz-review

#3616 (Release PR) Temporarily remove prance[osv] and swagger validation
  requirements.txt
  tests/test_swagger.py
Labels: Before release

#3621 Upgrade SQLAlchemy to latest version 1.3.1.
  requirements.txt
Labels: plz-review

#3624 Change default behavior of /candidates/totals/by_office/
  endpoints_walk.py
  tests/test_aggregates.py
  webservices/args.py
  webservices/resources/candidate_aggregates.py
  webservices/schemas.py
Labels: plz-review

#3619 update ofec_totals_combined_mv to fix ttl_fed_disb null problem
  data/migrations/V0125__ofec_totals_combined_mv_ttl_fed_disb_null.sql
Labels: plz-review

#3628 [MERGE WITH GIT FLOW] Temporarily block one IP address
  webservices/rest.py
Labels: Hotfix

#3610 Add all-day cache between 9am and 7:30pm ET
  webservices/rest.py
Labels: Before release, plz-review

#3644 use two_year_transaction_period in join for fec_fitem_sched_a/b
  webservices/common/models/itemized.py
Labels: plz-review

#3640 fix-mv-refresh-sequence
  webservices/flow.py
Labels: plz-review

#3645 Limit extra caching to /schedules/
  webservices/rest.py
Labels: Before release, plz-review
