Repository fecgov/openFEC, pull requests merged in 2019-10, with the labels that each got.

#3993 Remove eslint-plugin-no-unsanitized from package due to vulnerability
  package.json
Labels: Please review

#3984 update apispec to nonforked version
  requirements.txt
Labels: Please review, dependencies

#4002 Use actual counts for Schedule E efile endpoint
  webservices/resources/sched_e.py
Labels: Before release, Please review

#3998 Add retries to elasticsearch connection, fix unpublish logic for "all murs" reload
  webservices/legal_docs/current_cases.py
  webservices/utils.py
Labels: Before release, Please review

#4009 Add designation filters to committee history endpoints
  tests/test_committees.py
  webservices/args.py
  webservices/resources/committees.py
Labels: Please review

#4013 remove unused python libraries
  data/districts.dump
  data/election_dates.xlsx
  data/fips_states.csv
  data/natl_zccd_delim.csv
  data/nicknames.csv
  data/pacronyms.xlsx
  data/real_efile_to_form_line_numbers.xlsx
  manage.py
  requirements-dev.txt
  requirements.txt
Labels: Please review

#4014 Increase maximum number of committeeIDs to 10
  webservices/common/views.py
Labels: Please review

#4036 bump flask 1.0.2-->1.1.1
  requirements.txt
Labels: Please review

#4043 Add columns to committee_history_mv and filings_all_mv to help filtering to display cycles with either financial reports or with activity.
  data/migrations/V0168__add_filing_type_to_filings_all_mv.sql
  data/migrations/V0169__add_cycles_has_reports_to_ofec_committee_history_mv.sql
Labels: Please review

#4046 Remove unused partition code
  webservices/partition/__init__.py
  webservices/partition/base.py
  webservices/partition/utils.py
Labels: Please review

#4039 Add cycles_has_financial /activity in committee history and form_category in filings.
  tests/test_filings.py
  webservices/args.py
  webservices/common/models/committees.py
  webservices/common/models/filings.py
  webservices/docs.py
  webservices/resources/filings.py
Labels: Please review
