Repository fecgov/openFEC, pull requests merged in 2020-10, with the labels that each got.

#4648 update circle config
  .circleci/config.yml
Labels: Please review

#4656 [Migration V216, V217] Add sponsor_candidate_ids to two materialized views
  data/migrations/V0216__add_sponsor_id_ofec_committee_history_mv.sql
  data/migrations/V0217__add_sponsor_id_ofec_committee_detail_mv.sql
Labels: Please review

#4646 Bump sqlalchemy to 1.3.19
  requirements.txt
Labels: Security: moderate

#4658 [migration file V0218] automatic candidate to pac conversion
  data/migrations/V0218__ofec_committee_history_mv_add_pcc_to_pac_info.sql
  tests/test_committees.py
  webservices/common/models/committees.py
  webservices/docs.py
  webservices/flow.py
  webservices/resources/committees.py
  webservices/rest.py
Labels: Please review

#4669 Remove archived_mur_names.csv
  data/archived_mur_names.csv
Labels: Please review

#4665 Update cf cli to version 7
  .circleci/config.yml
  README.md
  tasks.py
Labels: Please review, Work: Infrastructure

#4672 Update README.md
  README.md
Labels: Documentation

#4673 Update README.md
  README.md
Labels: Documentation

#4666 Add sponsor_candidate_id to endpoint: /committees/
  tests/test_committees.py
  webservices/args.py
  webservices/common/models/committees.py
  webservices/common/views.py
  webservices/docs.py
  webservices/filters.py
  webservices/resources/committees.py
Labels: Please review

#4678 Modified rest.py to send RESTRICT_MESSAGE and 503 error code if IP address is blocked
  webservices/rest.py
Labels: hacktoberfest-accepted
