Repository fecgov/openFEC, pull requests merged in 2020-06, with the labels that each got.

#4398 Fix release build
  README.md
  manage.py
  requirements.txt
  tests/data/archived_mur_bad_citation.html
  tests/data/archived_mur_bad_pdf_doc.json
  tests/data/archived_mur_bad_subject.html
  tests/data/archived_mur_data.html
  tests/data/archived_mur_doc.json
  tests/data/archived_mur_empty_data.html
  tests/data/archived_mur_empty_doc.json
  tests/data/archived_mur_multi_part_data.html
  tests/data/archived_mur_multi_part_doc.json
  tests/test_load_legal_docs.py
  tests/test_map_citations_murs.py
  webservices/legal_docs/__init__.py
  webservices/legal_docs/load_legal_docs.py
Labels: Before release, Please review

#4397 [MERGE WITH GIT FLOW] [HOTFIX] Fix master build
  README.md
  manage.py
  requirements.txt
  tests/data/archived_mur_bad_citation.html
  tests/data/archived_mur_bad_pdf_doc.json
  tests/data/archived_mur_bad_subject.html
  tests/data/archived_mur_data.html
  tests/data/archived_mur_doc.json
  tests/data/archived_mur_empty_data.html
  tests/data/archived_mur_empty_doc.json
  tests/data/archived_mur_multi_part_data.html
  tests/data/archived_mur_multi_part_doc.json
  tests/test_load_legal_docs.py
  tests/test_map_citations_murs.py
  webservices/legal_docs/__init__.py
  webservices/legal_docs/load_legal_docs.py
Labels: Before release, Hotfix, Please review

#4401 Update URL for presidential data on API page
  webservices/docs.py
Labels: Please review

#4366 Add max ten (10) limits for additional fields
  tests/test_itemized.py
  webservices/common/views.py
  webservices/resources/sched_a.py
  webservices/resources/sched_b.py
  webservices/resources/sched_e.py
Labels: Before release, Please review

#4412 add pg_date indexes to fec_fitem_sched_a tables
  data/migrations/V0200__add_index_on_pg_date.sql
Labels: Please review

#4367 Add filter by load_date in sched_a
  tests/test_itemized.py
  webservices/args.py
  webservices/docs.py
  webservices/resources/sched_a.py
Labels: Please review

#4424 Update description of postgresql version in README
  README.md
Labels: Please review

#4423 Add deprecation notice to Schedule A for 'contributor_aggregate_ytd'
  webservices/args.py
  webservices/resources/sched_a.py
Labels: Please review

#4427 Add message to change sched-a sort to DESC
  webservices/resources/sched_a.py
Labels: Please review

#4426 Modify Schedule A endpoint description about last index.
  webservices/docs.py
Labels: Please review

#4380 Add flag ('use_pk_for_count') to only select primary key column for count query
  tests/test_api.py
  tests/test_counts.py
  webservices/common/counts.py
  webservices/common/models/itemized.py
  webservices/common/views.py
  webservices/resources/elections.py
  webservices/resources/filings.py
  webservices/resources/sched_a.py
  webservices/tasks/download.py
Labels: Please review

#4428 Remove confusing brackets in PR template
  PULL_REQUEST_TEMPLATE.md
Labels: Please review

#4430 resolve postgresql security vulnerability
  data/flyway/build.gradle
Labels: Please review, Security: high

#4431 Update V0201__add_index_on_is_individual_contbr_city_state.sql
  data/migrations/V0201__add_index_on_is_individual_contbr_city_state.sql
Labels: Please review
