Repository fecgov/openFEC, pull requests merged in 2020-04, with the labels that each got.

#4275 [MERGE WITH GIT FLOW] Hotfix: Fix downloads while using Schedule A routing setting
  webservices/common/models/base.py
Labels: Hotfix, Please review

#4279 move nplus one
  .circleci/config.yml
  requirements-dev.txt
  requirements.txt
Labels: dependencies

#4294 Add is_active to ofec_committee_history_mv.
  data/migrations/V0193__add_is_active_ofec_committee_history_mv.sql
  requirements-dev.txt
  requirements.txt
Labels: Please review

#4293 upgrade codecov@2.0.9 to 2.0.17
  requirements.txt
Labels: Please review, Security: moderate, dependencies

#4313 Add is_active to committee history endpoint
  tests/test_committees.py
  webservices/common/models/committees.py
  webservices/docs.py
Labels: Please review

#4307 [MERGE WITH GIT FLOW] Add feature flag to restrict API traffic
  webservices/rest.py
Labels: Hotfix, Please review

#4316 Refactor ofec_filings_amendments_all_mv
  data/migrations/V0194__ofec_filings_amendments_all_mv.sql
  manage.py
  tests/integration/test_amendment_chain.py
  webservices/flow.py
Labels: Please review

#4317 Set prod api instances to 10
  manifests/manifest_api_prod.yml
Labels: Before release, Please review

#4320 Update locust to python 3.7 compatible version (10.0)
  requirements-dev.txt
Labels: Please review
