Repository fecgov/openFEC, pull requests merged in 2020-08, with the labels that each got.

#4509 Remove sort expression for Schedule B
  webservices/common/models/itemized.py
  webservices/schemas.py
Labels: Please review, Work: Back-end, Work: Database

#4540 Add user_downloads prefix to downloads bucket
  tests/test_downloads.py
  webservices/tasks/download.py
Labels: Please review

#4543 Resolve bug in rest.py
  webservices/rest.py
Labels: Bug

#4548 Replace 'FEC Form' with 'Form' and update URLs
  webservices/docs.py
Labels: Documentation

#4544 Add deprecation notice to /communication-cost/ endpoint
  webservices/docs.py
Labels: deprecated

#4550 Unpin python in runtime.txt
  runtime.txt
Labels: Dependencies

#4542 Add deprecation policy link to swagger
  webservices/docs.py
Labels: Documentation

#4557 [MERGE WITH GIT FLOW] Hotfix/4538 fix api key signup load
  webservices/docs.py
  webservices/rest.py
  webservices/templates/swagger-ui.html
Labels: Bug, Hotfix

#4571 Snyk High - Bump Lodash from 4.17.17 to 4.17.20
  package-lock.json
  package.json
Labels: Please review, Security: high, Work: Front-end

#4572 Add more archived mur tables (V0210)
  data/migrations/V0210__add_mur_name.sql
Labels: Please review

#4581 Decrease celery worker disk quota, specify quota for other apps
  manifests/manifest_api_dev.yml
  manifests/manifest_api_prod.yml
  manifests/manifest_api_stage.yml
  manifests/manifest_celery_beat_dev.yml
  manifests/manifest_celery_beat_prod.yml
  manifests/manifest_celery_beat_stage.yml
  manifests/manifest_celery_worker_dev.yml
  manifests/manifest_celery_worker_prod.yml
  manifests/manifest_celery_worker_stage.yml
Labels: Please review, Work: Back-end

#4577 Create load_archived_murs and extract_pdf_text commands
  manage.py
  webservices/legal_docs/__init__.py
  webservices/legal_docs/archived_murs.py
  webservices/legal_docs/current_cases.py
Labels: Please review, Work: Back-end

#4594 Update deprecation notice
  webservices/docs.py
Labels: Before release, Documentation
