Repository fecgov/openFEC, pull requests merged in 2020-03, with the labels that each got.

#4240 [openFEC] Enable circleci pipeline
  .circleci/config.yml
  requirements.txt
Labels: Please review

#4239 recreate ofec_totals_pac_party_view to include totals from committee that changes committee_type
  data/migrations/V0188__ofec_totals_pac_party_vw.sql
  webservices/common/models/totals.py
Labels: Please review

#4246 Add endpoint communication_costs/aggregates/
  tests/test_spending_by_others.py
  webservices/args.py
  webservices/resources/aggregates.py
  webservices/rest.py
  webservices/schemas.py
Labels: Please review

#4247 modify ofec_candidate_totals_detail_mv to correct candidate totals for H6MD08549
  data/migrations/V0189__ofec_candidate_totals_detail_mv.sql
Labels: Please review

#4256 Update elasticsearch version in required services
  webservices/config.py
Labels: Please review

#4258 [MERGE WITH GITFLOW] Modify committee type in ofec_totals_pac_party_vw
  data/migrations/V0190__ofec_totals_pac_party_vw.sql
Labels: Please review

#4255 replace uglifyjs-webpack-plugin with tersor-webpack-plugin
  package-lock.json
  package.json
  webpack.production.config.js
Labels: Security: moderate

#4263 Delete ofec_totals_pacs_parties_mv
  data/migrations/V0191__drop_ofec_totals_pacs_parties.sql
  manage.py
  webservices/flow.py
Labels: Please review

#4266 add_pg_date_column_to_presidential_tables
  data/migrations/V0192__add_pg_date_column_to_presidential_tables.sql
Labels: Please review

#4269 [MERGE WITH GIT FLOW] Hotfix: Feature to separate Schedule A traffic
  webservices/common/models/base.py
  webservices/rest.py
Labels: Hotfix, Please review
