Repository fecgov/openFEC, pull requests merged in 2020-09, with the labels that each got.

#4605 Increase API memory in production and stage, remove extra celery-worker instance (targets release)
  manifests/manifest_api_prod.yml
  manifests/manifest_api_stage.yml
  manifests/manifest_celery_worker_dev.yml
Labels: Before release, Please review, Work: Back-end

#4600 Tell user why 'create_sample_db' task fails without 'SQLA_SAMPLE_DB_CONN'
  tasks.py
Labels: Please review, Work: Back-end, Work: Database

#4610 Add financial summary of Joint fundraising committee ( migration V0211 )
  data/migrations/V0211__ofec_totals_house_senate_mv.sql
  tests/test_totals.py
Labels: Please review

#4604 Fix locust tests by using separate download key
  locustfile.py
Labels: Please review, Work: Back-end

#4607 [do not merge before PR# 4610] add disclosure.dim_cmte_ie_inf table and enable data sync with source database
  data/migrations/V0212__add_DIM_CMTE_IE_INF_table.sql
Labels: Please review

#4618 Remove two broken endpoints
  endpoints_walk.py
  webservices/rest.py
Labels: Please review, Work: Back-end

#4619 Use primary-key only count for Schedules B and E
  webservices/resources/sched_b.py
  webservices/resources/sched_e.py
Labels: Please review, Work: Back-end

#4625 [Migration 0213]Add cand_cmte_linkage_alternate table
  data/migrations/V0213__add_leadership_pac_linkage.sql
Labels: Please review

#4632 Pin greenlet@0.4.16
  requirements.txt
Labels: Bug

#4617 [MERGE WITH GIT FLOW] Release/public 20200922
  data/migrations/V0211__ofec_totals_house_senate_mv.sql
  data/migrations/V0212__add_DIM_CMTE_IE_INF_table.sql
  locustfile.py
  package-lock.json
  requirements.txt
  tasks.py
  tests/test_totals.py
Labels: Please review

#4630 [migration 0214/215] add ofec_pcc_to_non_pcc_mv and exclude table
  data/migrations/V0214__add_ofec_pcc_conversion_exclude.sql
  data/migrations/V0215__add_ofec_pcc_to_non_pcc_mv.sql
  manage.py
  webservices/flow.py
Labels: Please review

#4639 Update dev api memory to match other spaces
  manifests/manifest_api_dev.yml
Labels: Before release, Please review
