Repository fecgov/openFEC, pull requests merged in 2020-01, with the labels that each got.

#4132 Remove reference to swagger-tools
  README.md
Labels: documentation

#4136 update docs.py
  webservices/docs.py
Labels: Bug, Work: Back-end, documentation

#4135 upgrade smart open related pkgs
  requirements.txt
  tasks.py
Labels: Please review

#4144 Remove nulls from cycles_has_activity in ofec_committee_history_mv
  data/migrations/V0176__remove_null_from_ofec_committee_history_mv.sql
  tests/integration/test_committees.py
Labels: Please review

#4145 Add filing_form and is_notice filters in sched_e.ScheduleEEfileView
  data/migrations/V0177__add_filing_form_real_efile_se_f57_vw.sql
  tests/test_itemized.py
  webservices/args.py
  webservices/common/models/itemized.py
  webservices/resources/sched_e.py
Labels: Please review

#4159 Make filings from unverified candidates available on filings webpage
  data/migrations/V0178__add_candid_to_ofec_filings_all_mv.sql
Labels: Please review

#4161 [HOTFIX - MERGE WITH GIT FLOW] Fix python runtime version
  README.md
  runtime.txt
Labels: Hotfix, Please review

#4123 Feature/4112 schedule h4 endpoint
  tests/factories.py
  tests/test_itemized.py
  webservices/args.py
  webservices/common/models/itemized.py
  webservices/docs.py
  webservices/resources/sched_h4.py
  webservices/rest.py
  webservices/schemas.py
  webservices/utils.py
Labels: Please review, Work: Back-end
