Repository fecgov/openFEC, pull requests merged in 2020-12, with the labels that each got.

#4705 Remove deprecated '/communication-costs/' endpoint (replaced by '/communication_costs/')
  endpoints_walk.py
  tests/test_costs.py
  webservices/docs.py
  webservices/resources/costs.py
  webservices/rest.py
  webservices/schemas.py
Labels: Please review

#4707 Remove unnecessary filters for `/committee/committee_id/totals`
  webservices/args.py
  webservices/resources/totals.py
Labels: Please review, Work: Back-end

#4711 Feature/update headers
  webservices/rest.py
Labels: Please review, Work: Front-end

#4712 Feature/cookie settings
  webservices/rest.py
  webservices/templates/swagger-ui.html
Labels: Please review, Work: Front-end

#4717 Use new aws-redis-elasticache service
  README.md
  manifests/manifest_api_dev.yml
  manifests/manifest_api_feature.yml
  manifests/manifest_api_prod.yml
  manifests/manifest_api_stage.yml
  manifests/manifest_celery_beat_dev.yml
  manifests/manifest_celery_beat_feature.yml
  manifests/manifest_celery_beat_prod.yml
  manifests/manifest_celery_beat_stage.yml
  manifests/manifest_celery_worker_dev.yml
  manifests/manifest_celery_worker_feature.yml
  manifests/manifest_celery_worker_prod.yml
  manifests/manifest_celery_worker_stage.yml
  manifests/manifest_task_dev.yml.template
  manifests/manifest_task_feature.yml.template
  manifests/manifest_task_prod.yml.template
  manifests/manifest_task_stage.yml.template
  webservices/config.py
  webservices/tasks/__init__.py
Labels: Please review, Work: Back-end

#4716 [MERGE WITH GIT FLOW] [HOTFIX] [Migration V0219] Use https for docquery
  data/migrations/V0219__update_docquery_https.sql
  tests/test_reports.py
  webservices/common/models/filings.py
  webservices/utils.py
Labels: Hotfix, Please review, Work: Back-end, Work: Database

#4732 Update README for ES7 upgrade
  README.md
Labels: Please review
