Repository fecgov/openFEC, pull requests merged in 2020-02, with the labels that each got.

#4167 fix Missing candidate_election_yr 2018 in ofec_candidate_history_mv for H6MD08549
  data/migrations/V0179__update_ofec_candidate_history_mv.sql
Labels: Please review

#4179 Add file structure for presidential data endpoints
  webservices/args.py
  webservices/common/models/__init__.py
  webservices/common/models/presidential.py
  webservices/docs.py
  webservices/resources/presidential.py
  webservices/rest.py
  webservices/schemas.py
  webservices/spec.py
Labels: Please review

#4176 Create base tables to support data for presidential map 2016 and 2020
  data/migrations/V0180__add_PRES_2016_2020_tables.sql
Labels: Please review

#4183 update ofec_candidate_totals_mv
  data/migrations/V0181__update_ofec_candidate_totals_mv.sql
Labels: Before release

#4188 Install packages for pytest in Circle
  .circleci/config.yml
Labels: Please review

#4181 [V0182] Add /presidential/contributions/by_candidate/
  data/migrations/V0182__add_ofec_presidential_by_candidate_vw.sql
  tests/factories.py
  tests/test_presidential.py
  webservices/args.py
  webservices/common/models/presidential.py
  webservices/docs.py
  webservices/resources/presidential.py
  webservices/schemas.py
  webservices/spec.py
Labels: Please review

#4190 [V0183]Feature/4178 add endpoint PresidentialByStateView
  data/migrations/V0183__add_ofec_presidential_by_state_vw.sql
  tests/factories.py
  tests/test_presidential.py
  webservices/common/models/presidential.py
  webservices/resources/presidential.py
  webservices/schemas.py
Labels: Please review

#4189 [V0184] Make endpoint /presidential/financial_summary/
  data/migrations/V0184__add_ofec_presidential_summary_vw.sql
  tests/factories.py
  tests/test_presidential.py
  webservices/common/models/presidential.py
  webservices/resources/presidential.py
  webservices/schemas.py
Labels: Please review

#4194 [HOTFIX][MERGE WITH GIT FLOW] Pin werkzeug version
  requirements.txt
Labels: Hotfix, Please review

#4199 [V0185]Feature/4170 add endpoint presidential by size
  data/migrations/V0185__add_ofec_presidential_by_size_vw.sql
  tests/factories.py
  tests/test_presidential.py
  webservices/args.py
  webservices/common/models/presidential.py
  webservices/docs.py
  webservices/resources/presidential.py
Labels: Please review

#4197 [V0186] Add /presidential/coverage_end_date/
  data/migrations/V0186__add_ofec_presidential_coverage_date_vw.sql
  tests/factories.py
  tests/test_presidential.py
  webservices/common/models/presidential.py
  webservices/resources/presidential.py
  webservices/schemas.py
Labels: Please review

#4205 Add missing fields to financial summary
  webservices/common/models/presidential.py
Labels: Please review

#4209 Update 'most_recent' filters to always include null values
  tests/test_itemized.py
  webservices/args.py
  webservices/docs.py
  webservices/resources/sched_e.py
Labels: Please review

#4220 Add 'transfers_from_affiliated_committees' field to output
  webservices/common/models/presidential.py
Labels: Please review

#4216 Update gunicorn to 19.10.0
  requirements.txt
Labels: Please review

#4217 correct the value of most_recent for F24
  data/migrations/V0187__add_F24_version.sql
Labels: Please review

#4222 Add bubble endpoints description.
  webservices/args.py
  webservices/common/models/presidential.py
  webservices/docs.py
  webservices/resources/presidential.py
Labels: Please review

#4225 Conditionally hide presidential section from docs
  webservices/spec.py
Labels: Before release, Please review
