Repository fecgov/openFEC, pull requests merged in 2021-11, with the labels that each got.

#4977 [MERGE WITH GITFLOW] Release/public 20211102
  webservices/tasks/__init__.py
  webservices/tasks/legal_docs.py
  webservices/tasks/refresh_db.py
Labels: release-branch

#4978 Send to slack alerts and bots channels error message when refresh db fails
  webservices/tasks/refresh_db.py
Labels: Please review, Before release

#4983 upgrade-psycopg2-binary-fix-circleci-build
  requirements.txt
Labels: Please review

#4985 [MERGE WITH GITFLOW] upgrade-psycopg2-binary-fix-circleci-build
  requirements.txt
Labels: Please review, Hotfix

#4984 4975-Make API changes to allow for registration date default sort
  data/migrations/V0238__add_first_f1_index.sql
  tests/test_committees.py
  webservices/common/models/committees.py
Labels: Please review, Work: Back-end

#4992 Add disbursement percents to schedule_b_by_recipient endpoint
  data/migrations/V0239__ofec_sched_b_aggregate_recipient_mv.sql
  manage.py
  tests/test_aggregates.py
  webservices/common/models/aggregates.py
  webservices/flow.py
  webservices/schemas.py
Labels: Please review
