Repository fecgov/openFEC, pull requests merged in 2021-03, with the labels that each got.

#4804 Update requests to latest version
  requirements.txt
Labels: Please review

#4802 Use `UNION ALL` subqueries for 2-year-transaction-period for Schedules A and B
  tests/integration/test_tsvector_generation.py
  tests/test_itemized.py
  webservices/common/views.py
  webservices/resources/sched_a.py
  webservices/resources/sched_b.py
  webservices/resources/sched_e.py
Labels: Please review, Work: Back-end, Work: Database

#4816 Create issue-template.md
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: Please review

#4819 [Merge to release] Remove 2-year-transaction period from UNION ALL fields
  webservices/resources/sched_a.py
  webservices/resources/sched_b.py
Labels: Before release, Please review

#4817 [MERGE WITH GIT FLOW] Release/public 20210330
  .github/ISSUE_TEMPLATE/issue-template.md
  PULL_REQUEST_TEMPLATE.md
  data/migrations/V0222__add_index_idx_ofec_totals_combined_mv_cmte_id_cycle.sql
  requirements.txt
  tests/integration/test_tsvector_generation.py
  tests/test_itemized.py
  webservices/common/views.py
  webservices/resources/sched_a.py
  webservices/resources/sched_b.py
  webservices/resources/sched_e.py
Labels: Please review
