Repository fecgov/openFEC, pull requests merged in 2021-07, with the labels that each got.

#4900 Add filters to` /totals/entity_type/` to support PAC/Party totals data table
  data/migrations/V0232__add_totals_fields.sql
  tests/factories.py
  tests/integration/test_integration.py
  tests/test_totals.py
  webservices/args.py
  webservices/common/models/totals.py
  webservices/resources/totals.py
  webservices/schemas.py
Labels: Please review, Work: Back-end, Work: Database

#4908 Remove old elasticsearch command from the documentation.
  README.md
Labels: Please review

#4909 Add leadership sponsor and org type to /totals/by_entity/
  data/migrations/V0233__add_sponsors_and_org_type.sql
  data/migrations/V0234__add_ofec_pac_sponsor_candidate_list_per_cycle.sql
  tests/factories.py
  tests/test_committees.py
  tests/test_totals.py
  webservices/args.py
  webservices/common/models/candidates.py
  webservices/common/models/totals.py
  webservices/resources/totals.py
  webservices/schemas.py
Labels: Please review

#4911 Run `npm audit fix`
  package-lock.json
Labels: Please review

#4919 Don't add coalesce if sort index can't be null
  webservices/utils.py
Labels: High priority, Please review, Work: Back-end

#4922 Upgrade networkx to v2.6.2
  requirements.txt
Labels: Please review

#4923 [MERGE WITH GITFLOW] Release/public 20210728
  webservices/utils.py
Labels: Please review
