Repository fecgov/openFEC, pull requests merged in 2021-05, with the labels that each got.

#4845 Cache cmte and cand totals endpoint.
  webservices/rest.py
Labels: Before release, Please review

#4844 Simplify follower (`SQLA_FOLLOWER`) logic
  README.md
  webservices/common/models/base.py
  webservices/rest.py
Labels: Before release, Please review, Work: Back-end

#4860 cache-cmte-and-cand-totals-endpoint.
  webservices/rest.py
Labels: Please review

#4865 Modify database function report_fec_url
  data/migrations/V0227__modify_report_fec_url.sql
  tests/integration/test_filings.py
Labels: Please review
