Repository fecgov/openFEC, pull requests merged in 2021-08, with the labels that each got.

#4926 [MERGE WITH GITFLOW] Release/public 20210810
  requirements.txt
Labels: Please review

#4930 Create delete doc method from es
  manage.py
  tests/integration/test_advisory_opinions.py
  webservices/legal_docs/__init__.py
  webservices/legal_docs/advisory_opinions.py
  webservices/legal_docs/es_management.py
Labels: Please review, Before release

#4934 Fix circleCI builds: Allow OS release info to change
  .circleci/config.yml
Labels: Please review, Before release

#4936 Add first Form 1 date to committees endpoints
  data/migrations/V0235__first_f1_ofec_committee_detail_mv.sql
  webservices/common/models/committees.py
  webservices/docs.py
Labels: Please review, Work: Back-end, Work: Database

#4937 [MERGE WITH GIT FLOW] Release/public 20210824
  .circleci/config.yml
  manage.py
  tests/integration/test_advisory_opinions.py
  webservices/legal_docs/__init__.py
  webservices/legal_docs/advisory_opinions.py
  webservices/legal_docs/es_management.py
Labels: Please review
