Repository fecgov/openFEC, pull requests merged in 2021-02, with the labels that each got.

#4756 Add new amount filters to debts
  tests/test_sched_d.py
  webservices/args.py
  webservices/resources/sched_d.py
Labels: Please review, Work: Back-end

#4760 4744-show-entity-names-for-individual-types
  tests/integration/test_advisory_opinions.py
  webservices/legal_docs/advisory_opinions.py
Labels: Please review

#4762 fix-ao-data-load-issue
  tests/integration/test_advisory_opinions.py
  webservices/legal_docs/advisory_opinions.py
Labels: Before release, Please review

#4782 4766 bump lodash 4.17.20 > 4.17.21
  package-lock.json
  package.json
Labels: Please review, Work: Front-end
