Repository fecgov/openFEC, pull requests merged in 2021-01, with the labels that each got.

#4728 [MERGE WITH GIT FLOW] Release/public 20210105
  README.md
  manifests/manifest_api_dev.yml
  manifests/manifest_api_feature.yml
  manifests/manifest_api_prod.yml
  manifests/manifest_api_stage.yml
  manifests/manifest_celery_beat_dev.yml
  manifests/manifest_celery_beat_feature.yml
  manifests/manifest_celery_beat_prod.yml
  manifests/manifest_celery_beat_stage.yml
  manifests/manifest_celery_worker_dev.yml
  manifests/manifest_celery_worker_feature.yml
  manifests/manifest_celery_worker_prod.yml
  manifests/manifest_celery_worker_stage.yml
  manifests/manifest_task_dev.yml.template
  manifests/manifest_task_feature.yml.template
  manifests/manifest_task_prod.yml.template
  manifests/manifest_task_stage.yml.template
  webservices/config.py
  webservices/tasks/__init__.py
  webservices/utils.py
Labels: Please review

#4737 Replace `xml.etree.ElementTree.parse` with its `defusedxml` equivalent
  requirements.txt
  webservices/legal_docs/statutes.py
Labels: Before release, Please review

#4743 [MERGE WITH GITFLOW] Release/public 20210119
  README.md
  requirements.txt
  webservices/legal_docs/statutes.py
Labels: release-branch

#4752 Add leadership pac committee rows in return result
  tests/factories.py
  tests/test_committees.py
  webservices/common/models/links.py
  webservices/resources/committees.py
Labels: Before release, Please review
