Repository fecgov/openFEC, pull requests merged in 2021-06, with the labels that each got.

#4884 fix schedule_b efile download multi same rows
  webservices/schemas.py
Labels: Before release, Please review

#4881 Add fields to /totals/pac-party/
  data/migrations/V0228__modify_ofec_totals_combined.sql
  tests/test_totals.py
  webservices/common/models/totals.py
Labels: Please review, Work: Back-end, Work: Database

#4890 Update celery worker memory
  manifests/manifest_celery_worker_dev.yml
  manifests/manifest_celery_worker_prod.yml
Labels: Please review

#4893 Add leadership PAC sponsor list to /committees/ endpoint
  data/migrations/V0229__add_ofec_pac_sponsor_candidate.sql
  tests/factories.py
  tests/test_candidates.py
  tests/test_committees.py
  webservices/common/models/candidates.py
  webservices/common/models/committees.py
  webservices/schemas.py
Labels: Please review

#4891 Rename totals and reports endpoints to use `entity_type` instead of `committee_type`
  tests/test_downloads.py
  tests/test_reports.py
  tests/test_totals.py
  webservices/args.py
  webservices/docs.py
  webservices/exceptions.py
  webservices/resources/reports.py
  webservices/resources/totals.py
  webservices/rest.py
Labels: Before release, Please review

#4897 [MERGE WITH GIT FLOW] Release/public 20210629
  data/migrations/V0228__modify_ofec_totals_combined.sql
  data/migrations/V0229__add_ofec_pac_sponsor_candidate.sql
  manifests/manifest_celery_worker_dev.yml
  manifests/manifest_celery_worker_prod.yml
  tests/factories.py
  tests/test_candidates.py
  tests/test_committees.py
  tests/test_downloads.py
  tests/test_reports.py
  tests/test_totals.py
  webservices/args.py
  webservices/common/models/candidates.py
  webservices/common/models/committees.py
  webservices/common/models/totals.py
  webservices/docs.py
  webservices/exceptions.py
  webservices/resources/reports.py
  webservices/resources/totals.py
  webservices/rest.py
  webservices/schemas.py
Labels: Please review

#4894 Add percentages to support PAC snapshot
  tests/test_totals.py
  tests/test_utils.py
  webservices/common/models/totals.py
  webservices/schemas.py
  webservices/utils.py
Labels: Please review, Work: Back-end

#4898 Fix typo in API docs
  webservices/docs.py
Labels: Please review

#4899 Add admin fines additional parameters
  data/migrations/V0230__create_table_af_case_disposition.sql
  tests/integration/test_current_cases.py
  webservices/legal_docs/current_cases.py
  webservices/legal_docs/es_management.py
Labels: Please review

#4902 [Merge after V230]Add migration file for af_number_rad_civil_pnlty_updt
  data/migrations/V0231__create_af_number_rad_civil_pnlty_updt.sql
Labels: Please review
