Repository fecgov/openFEC, pull requests merged in 2022-02, with the labels that each got.

#5045 Fix 404 error when a case is unpublished
  webservices/legal_docs/current_cases.py
Labels: Bug

#5040 [MERGE WITH GITFLOW] Release/public 20220208
  .circleci/config.yml
  webservices/tasks/__init__.py
  webservices/tasks/legal_docs.py
Labels: release-branch

#5044 Upgrade flyway to 8.4.3
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
Labels: Please review

#5050 Add three new columns into ofec_candidate_totals_mv migration file
  data/migrations/V0242__add_3_columns_ofec_candidate_totals_mv.sql
Labels: Please review

#5049 upgrade postgres circleci docker image
  .circleci/config.yml
Labels: Please review

#5042 4892- Add committee_type filter and test
  tests/test_reports.py
  webservices/args.py
  webservices/docs.py
  webservices/resources/reports.py
Labels: Please review

#5054 Switch column other_receipts to other_political_committee_contributions
  data/migrations/V0243__fix_columns_name_ofec_candidate_totals_mv.sql
Labels: Please review

#5057 [MERGE WITH GITFLOW] Release/public 20220222
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
  data/migrations/V0242__add_3_columns_ofec_candidate_totals_mv.sql
  data/migrations/V0243__fix_columns_name_ofec_candidate_totals_mv.sql
  manifests/manifest_celery_worker_dev.yml
  tests/test_reports.py
  webservices/args.py
  webservices/docs.py
  webservices/legal_docs/current_cases.py
  webservices/resources/reports.py
Labels: release-branch

#5056 Add filters to AggregateByOfficeView and AggregateByOfficeByPartyView
  tests/test_aggregates.py
  webservices/args.py
  webservices/common/models/candidates.py
  webservices/resources/candidate_aggregates.py
  webservices/schemas.py
Labels: Please review
