Repository fecgov/openFEC, pull requests merged in 2022-01, with the labels that each got.

#5022 Change idx to row number in ofec_sched_b_aggregate_recipient_mv.
  data/migrations/V0241__idx_ofec_sched_b_aggregate_recipient_mv.sql
Labels: Please review

#5023 Revert node/npm version in package files
  package-lock.json
  package.json
Labels: Please review

#5024 Fix npm warnings in circleci builds
  .circleci/config.yml
  package-lock.json
  package.json
Labels: Please review, Before release

#5025 [MERGE WITH GITFLOW] Release/public 20220125
  .circleci/config.yml
  data/migrations/V0241__idx_ofec_sched_b_aggregate_recipient_mv.sql
  package-lock.json
  package.json
Labels: release-branch

#5033 Modify reload AOs to handle multiple AOs to ES
  webservices/tasks/__init__.py
  webservices/tasks/legal_docs.py
Labels: Please review, Before release
