Repository fecgov/openFEC, pull requests merged in 2022-11, with the labels that each got.

#5274 [MERGE WITH GITFLOW] Increase api memory to 2.5G
  manifests/manifest_api_dev.yml
  manifests/manifest_api_prod.yml
  manifests/manifest_api_stage.yml
Labels: Hotfix

#5276 5266 & 5262 Upgrade flyway 9.7.0
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
Labels: Please review

#5275 Create model CommitteeHistoryProfile and Refactor CommitteeHistory join
  tests/factories.py
  tests/integration/test_committees.py
  tests/test_committees.py
  webservices/common/models/committees.py
  webservices/resources/committees.py
  webservices/resources/search.py
  webservices/rest.py
  webservices/schemas.py
Labels: Please review, High priority

#5273 [MERGE WITH GITFLOW] Release/public 20221109
  tests/factories.py
  tests/integration/test_committees.py
  tests/test_aggregates.py
  tests/test_committees.py
  webservices/common/models/committees.py
  webservices/resources/candidate_aggregates.py
  webservices/resources/committees.py
  webservices/resources/search.py
  webservices/rest.py
  webservices/schemas.py
Labels: release-branch

#5285 [MERGE WITH GITFLOW] Release/public 20221122
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
  manifests/manifest_api_dev.yml
  manifests/manifest_api_prod.yml
  manifests/manifest_api_stage.yml
Labels: release-branch
