Repository fecgov/openFEC, pull requests merged in 2022-03, with the labels that each got.

#5060 upgrade swagger-ui-dist to latest
  package-lock.json
  package.json
  webservices/templates/swagger-ui.html
Labels: Please review, Before release

#5070 [MERGE WITH GITFLOW] Release/public 20220308
  package-lock.json
  package.json
  tests/test_aggregates.py
  webservices/args.py
  webservices/common/models/candidates.py
  webservices/legal_docs/current_cases.py
  webservices/resources/candidate_aggregates.py
  webservices/schemas.py
  webservices/templates/swagger-ui.html
Labels: release-branch

#5073 Feature/Upgrade flyway to 852
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
Labels: Please review

#5076 5041-Update Committee type I language
  data/migrations/V0244__modify_committee_type_function.sql
  webservices/docs.py
Labels: Please review

#5085 5043- Remove type filter
  webservices/args.py
  webservices/docs.py
  webservices/resources/reports.py
Labels: Please review

#5089 Add columns state district in candidate_totals_mv
  data/migrations/V0245__add_state_district_ofec_candidate_totals_mv.sql
Labels: Please review
