Repository fecgov/openFEC, pull requests merged in 2022-10, with the labels that each got.

#5248 Fix null value in committee name
  data/migrations/V0262__ofec_sched_e_mv_add_coalesce.sql
Labels: Please review

#5241 Update refresh interval
  webservices/tasks/__init__.py
  webservices/tasks/legal_docs.py
Labels: Please review

#5254 [MERGE WITH GITFLOW] Release/public 20221011
  .circleci/config.yml
  data/migrations/V0262__ofec_sched_e_mv_add_coalesce.sql
  webservices/tasks/__init__.py
  webservices/tasks/legal_docs.py
Labels: release-branch

#5255 Add filer_name_text in ofec_reports_ie_only_mv
  data/migrations/V0263__ofec_reports_ie_only_mv_add_filer_name_text.sql
Labels: Please review

#5257 add committee_name in reports_ie_only_mv
  data/migrations/V0264__ofec_reports_ie_only_mv_add_committee_name.sql
Labels: Please review

#5256 Fix invalid districts in /candidates/totals/aggregates/
  tests/test_aggregates.py
  webservices/resources/candidate_aggregates.py
Labels: Please review

#5250 ADR additional parameters
  tests/integration/test_current_cases.py
  webservices/legal_docs/current_cases.py
  webservices/legal_docs/es_management.py
Labels: Please review

#5260 Fix broken reports_ie_only endpoint
  tests/test_reports.py
  webservices/args.py
  webservices/common/models/reports.py
  webservices/resources/reports.py
  webservices/schemas.py
Labels: Please review, Before release

#5261 [MERGE WITH GITFLOW] Release/public 20221025
  data/migrations/V0263__ofec_reports_ie_only_mv_add_filer_name_text.sql
  data/migrations/V0264__ofec_reports_ie_only_mv_add_committee_name.sql
  manifests/manifest_api_dev.yml
  manifests/manifest_api_prod.yml
  manifests/manifest_api_stage.yml
  tests/integration/test_current_cases.py
  tests/test_aggregates.py
  tests/test_reports.py
  webservices/args.py
  webservices/common/models/reports.py
  webservices/legal_docs/current_cases.py
  webservices/legal_docs/es_management.py
  webservices/resources/candidate_aggregates.py
  webservices/resources/reports.py
  webservices/schemas.py
Labels: release-branch

#5271 Display states with election during a given election year by candidate/totals/aggregate
  tests/test_aggregates.py
  webservices/resources/candidate_aggregates.py
Labels: Please review
