Repository fecgov/openFEC, pull requests merged in 2022-08, with the labels that each got.

#5204 [MERGE WITH GITFLOW]Release/public 20220802
  data/migrations/V0249__add_function_get_committee_label.sql
  data/migrations/V0250__add_committee_label_ofec_committee_history_mv.sql
  requirements.txt
  tests/test_filings.py
  webservices/args.py
  webservices/common/models/committees.py
  webservices/docs.py
  webservices/resources/filings.py
Labels: release-branch

#5209 Add filer_name_text filter in filings and efilings
  tests/test_filings.py
  webservices/args.py
  webservices/common/models/filings.py
  webservices/docs.py
  webservices/exceptions.py
  webservices/resources/filings.py
  webservices/schemas.py
Labels: Please review, Before release

#5211 Add spender_name_text in sched_e_mv
  data/migrations/V0255__ofec_sched_e_mv_add_spender_name_text.sql
Labels: Please review, Before release

#5210 Add filer_name_text filter in reports and 3 efiling reports endpoints
  tests/test_filings.py
  tests/test_reports.py
  webservices/args.py
  webservices/common/models/filings.py
  webservices/common/models/reports.py
  webservices/exceptions.py
  webservices/resources/reports.py
  webservices/schemas.py
Labels: Please review, Before release

#5212 Add spender_name_text filter in /schedules/schedule_e/
  tests/test_itemized.py
  webservices/args.py
  webservices/common/models/itemized.py
  webservices/docs.py
  webservices/resources/sched_e.py
  webservices/schemas.py
Labels: Please review, Before release

#5186 4958-upgrade flask
  .flaskenv
  README.md
  bin/cf_env_setup.sh
  bin/run.sh
  cli.py
  manage.py
  manifests/manifest_task_dev.yml.template
  manifests/manifest_task_feature.yml.template
  requirements-dev.txt
  requirements.txt
  tasks.py
  webservices/legal_docs/__init__.py
  webservices/legal_docs/es_management.py
  webservices/legal_docs/regulations.py
  webservices/legal_docs/statutes.py
  webservices/rest.py
Labels: Please review

#5216 [MERGE WITH GITFLOW] Release/public 20220823
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
  data/migrations/V0251__ofec_filings_all_mv_add_filer_name_text.sql
  data/migrations/V0252__ofec_report_presidential_mv_add_filer_name_text.sql
  data/migrations/V0253__ofec_report_house_senate_mv_add_filer_name_text.sql
  data/migrations/V0254__ofec_report_pac_party_mv_add_filer_name_text.sql
  data/migrations/V0255__ofec_sched_e_mv_add_spender_name_text.sql
  requirements.txt
  tests/test_filings.py
  tests/test_itemized.py
  tests/test_reports.py
  webservices/args.py
  webservices/common/models/filings.py
  webservices/common/models/itemized.py
  webservices/common/models/reports.py
  webservices/docs.py
  webservices/exceptions.py
  webservices/resources/filings.py
  webservices/resources/reports.py
  webservices/resources/sched_e.py
  webservices/schemas.py
Labels: release-branch

#5223 Remove duplicate indexes on real_efile_sb4 table and also create index on real_efile_sa7 table
  data/migrations/V0042__add_comid_index_to_real_efile_tables.sql
  data/migrations/V0256__fix_duplicate_indexes_on_real_efile_tables.sql
Labels: Please review

#5228 upgrade flyway
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
Labels: Please review, Before release

#5229 5203- Upgrade circleci docker images (python 3.8 and PG 13.5), pin flake8
  .circleci/config.yml
  requirements.txt
Labels: Please review
