Repository fecgov/openFEC, pull requests merged in 2023-10, with the labels that each got.

#5598 Upgrade gitpython to 3.1.35
  requirements.txt
Labels: Please review

#5607 Replace CandidateTotals with CandidateTotalsDetail
  tests/factories.py
  tests/integration/test_candidate_committee_totals.py
  tests/test_totals.py
  webservices/common/models/totals.py
  webservices/resources/totals.py
  webservices/rest.py
  webservices/schemas.py
Labels: Please review

#5606 5577-remove deprecated filter from schedule_d endpoint
  tests/test_sched_d.py
  webservices/args.py
  webservices/common/models/itemized.py
  webservices/docs.py
  webservices/resources/sched_d.py
Labels: Please review

#5623 Upgrade flyway v9.22.3
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
Labels: Please review

#5618 [MERGE WITH GITFLOW] Release/public 20231024
  requirements.txt
  tests/common.py
  tests/factories.py
  tests/integration/test_candidate_committee_totals.py
  tests/test_sched_d.py
  tests/test_totals.py
  webservices/args.py
  webservices/common/models/itemized.py
  webservices/common/models/totals.py
  webservices/docs.py
  webservices/resources/sched_d.py
  webservices/resources/totals.py
  webservices/rest.py
  webservices/schemas.py
Labels: release-branch

#5624 Fix sort validation to skip 500 error
  tests/test_aggregates.py
  tests/test_spending_by_others.py
  webservices/args.py
  webservices/resources/candidate_aggregates.py
  webservices/resources/spending_by_others.py
Labels: Please review, Before release

#5625 Create celery task to delete snapshots
  webservices/legal_docs/es_management.py
  webservices/tasks/__init__.py
  webservices/tasks/legal_docs.py
Labels: Please review

#5630 Add committee_id validation
  tests/factories.py
  tests/integration/test_amendment_chain.py
  tests/integration/test_candidate_committee_totals.py
  tests/integration/test_committees.py
  tests/integration/test_filings.py
  tests/test_aggregates.py
  tests/test_committees.py
  tests/test_costs.py
  tests/test_filing_resources.py
  tests/test_filings.py
  tests/test_inaugural_donations.py
  tests/test_itemized.py
  tests/test_reports.py
  tests/test_sched_d.py
  tests/test_spending_by_others.py
  tests/test_totals.py
  webservices/args.py
  webservices/docs.py
  webservices/exceptions.py
  webservices/resources/candidates.py
  webservices/resources/committees.py
  webservices/resources/filings.py
  webservices/resources/reports.py
  webservices/resources/totals.py
  webservices/utils.py
Labels: Please review
