Repository fecgov/openFEC, pull requests merged in 2023-11, with the labels that each got.

#5644 5609-add form_line_number to Schedule_CDEFH
  tests/test_itemized.py
  tests/test_sched_c.py
  tests/test_sched_d.py
  webservices/args.py
  webservices/common/models/itemized.py
  webservices/docs.py
  webservices/exceptions.py
  webservices/resources/sched_c.py
  webservices/resources/sched_d.py
  webservices/resources/sched_e.py
  webservices/resources/sched_f.py
  webservices/resources/sched_h4.py
  webservices/schemas.py
  webservices/utils.py
Labels: Please review, Before release, breaking change

#5643 Add candidate_id validation
  tests/factories.py
  tests/integration/test_candidate_committee_totals.py
  tests/integration/test_candidates.py
  tests/integration/test_filings.py
  tests/test_aggregates.py
  tests/test_candidates.py
  tests/test_committees.py
  tests/test_costs.py
  tests/test_filings.py
  tests/test_itemized.py
  tests/test_presidential.py
  tests/test_sched_e.py
  tests/test_spending_by_others.py
  tests/test_totals.py
  webservices/args.py
  webservices/exceptions.py
  webservices/resources/candidates.py
  webservices/resources/committees.py
  webservices/resources/filings.py
  webservices/resources/reports.py
  webservices/resources/sched_e.py
  webservices/resources/totals.py
  webservices/utils.py
Labels: Please review, Before release

#5645 [MERGE WITH GITFLOW] Release/public 20231122
  tests/factories.py
  tests/integration/test_candidate_committee_totals.py
  tests/integration/test_candidates.py
  tests/integration/test_filings.py
  tests/test_aggregates.py
  tests/test_candidates.py
  tests/test_committees.py
  tests/test_costs.py
  tests/test_filings.py
  tests/test_itemized.py
  tests/test_presidential.py
  tests/test_sched_c.py
  tests/test_sched_d.py
  tests/test_sched_e.py
  tests/test_spending_by_others.py
  tests/test_totals.py
  webservices/args.py
  webservices/common/models/itemized.py
  webservices/docs.py
  webservices/exceptions.py
  webservices/resources/aggregates.py
  webservices/resources/audit.py
  webservices/resources/candidate_aggregates.py
  webservices/resources/candidates.py
  webservices/resources/committees.py
  webservices/resources/costs.py
  webservices/resources/dates.py
  webservices/resources/elections.py
  webservices/resources/filings.py
  webservices/resources/large_aggregates.py
  webservices/resources/legal.py
  webservices/resources/operations_log.py
  webservices/resources/presidential.py
  webservices/resources/rad_analyst.py
  webservices/resources/reports.py
  webservices/resources/sched_a.py
  webservices/resources/sched_b.py
  webservices/resources/sched_c.py
  webservices/resources/sched_d.py
  webservices/resources/sched_e.py
  webservices/resources/sched_f.py
  webservices/resources/sched_h4.py
  webservices/resources/search.py
  webservices/resources/spending_by_others.py
  webservices/resources/totals.py
  webservices/schemas.py
  webservices/utils.py
Labels: release-branch

#5651 Fix filter by multi candidate_id for reports/entity_type
  tests/test_filters.py
  webservices/args.py
  webservices/resources/reports.py
Labels: Please review, Before release
