Repository fecgov/openFEC, pull requests merged in 2023-08, with the labels that each got.

#5530 Add sortable field: party_full in /candidates/totals/
  webservices/resources/candidate_aggregates.py
Labels: Please review

#5520 [MERGE WITH GITFLOW] Release/public 20230808
  data/migrations/V0282__add_sched_d_line_num_index.sql
  requirements.txt
  webservices/resources/candidate_aggregates.py
  webservices/resources/legal.py
Labels: release-branch

#5544 [HOTFIX - MERGE WITH GITFLOW] 5526 address
  src/components/Footer.js
Labels: Please review, Work: Front-end, Hotfix

#5541 Rename Document YYYY as "Debt Settlement Plan YYYY"
  webservices/utils.py
Labels: Please review

#5547 suppress specific pytest warnings
  setup.cfg
Labels: Please review

#5553 re-label debt settlement plan
  webservices/decoders.py
  webservices/utils.py
Labels: Please review, Before release

#5559 Add test case for sorting validation
  tests/test_aggregates.py
Labels: Please review

#5548 5522-add cmte_tp, filing_form filters add dep notice
  data/migrations/V0283__add_sched_d_filters_rm_nulls.sql
  tests/test_sched_d.py
  webservices/args.py
  webservices/common/models/itemized.py
  webservices/docs.py
  webservices/resources/sched_d.py
Labels: Please review

#5556 upgrade gitpython and certifi
  requirements.txt
Labels: Please review
