Repository fecgov/openFEC, pull requests merged in 2023-06, with the labels that each got.

#5466 Update full_text field to keyword type
  tests/test_itemized.py
  tests/test_sched_c.py
  webservices/args.py
  webservices/exceptions.py
Labels: Please review

#5464 [MERGE WITH GITFLOW] Release/public 20230606
  .pre-commit-config.yaml
  .prettierrc
  endpoints_walk.py
  package-lock.json
  package.json
  src/components/Footer.js
  tests/test_aggregates.py
  tests/test_costs.py
  webservices/args.py
  webservices/docs.py
  webservices/resources/candidate_aggregates.py
  webservices/resources/costs.py
  webservices/rest.py
Labels: Please review, release-branch

#5470 5364-add pdf_url to h4 mv
  data/migrations/V279__add_pdfurl_to_h4.sql
Labels: Please review

#5471 5364-Fix H4 migration file naming issue
  data/migrations/V0278__add_pdfurl_to_h4.sql
  data/migrations/V278__h4_add_sort.sql
Labels: Please review

#5472 5364 add pdf_url to h4 endpoint results
  webservices/common/models/itemized.py
Labels: Please review

#5473 Upgrade flyway to v9.19.4
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
Labels: Please review, Before release

#5480 add presidential tables for 2008 and 2012 cycles
  data/migrations/V0279__add_presidential_2008_tables.sql
  data/migrations/V0280__add_presidential_2012_tables.sql
  data/migrations/V0281__update_presidential_views_to_include_2008_2012_data.sql
Labels: Please review
