Repository fecgov/openFEC, pull requests merged in 2023-04, with the labels that each got.

#5387 upgrade redis to 4.5.4
  requirements.txt
Labels: Please review

#5390 Fix es snapshot bug
  webservices/tasks/legal_docs.py
Labels: Please review

#5391 add fec_fitem_sched_ab_2023_2024 tables
  data/migrations/V0270__add_fec_fitem_sched_ab_2023_2024.sql
Labels: Please review

#5388 [MERGE WITH GITFLOW] Release/public 20230411
  README.md
  cli.py
  data/migrations/V0269__ofec_sched_e_mv_add_exp_purpose.sql
  requirements.txt
  tasks.py
  tests/integration/test_advisory_opinions.py
  tests/integration/test_current_cases.py
  tests/test_itemized.py
  tests/test_legal.py
  tests/test_load_legal_docs.py
  webservices/legal_docs/__init__.py
  webservices/legal_docs/advisory_opinions.py
  webservices/legal_docs/archived_murs.py
  webservices/legal_docs/current_cases.py
  webservices/legal_docs/es_management.py
  webservices/legal_docs/regulations.py
  webservices/legal_docs/statutes.py
  webservices/resources/legal.py
  webservices/tasks/__init__.py
  webservices/tasks/legal_docs.py
Labels: release-branch

#5407 [MERGE WITH GIT FLOW] Hotfix/use new codecov uploader
  .circleci/config.yml
  requirements.txt
Labels: Please review

#5413 Increase snapshot sleep time to 60s
  webservices/tasks/legal_docs.py
Labels: Please review

#5410 Add report info to debts endpoint
  tests/test_sched_d.py
  webservices/args.py
  webservices/common/models/itemized.py
  webservices/docs.py
  webservices/resources/sched_d.py
Labels: Please review

#5419 Update legal search description for pagination
  webservices/docs.py
Labels: Please review

#5415 Remove schedule A routing logic
  webservices/common/models/base.py
  webservices/rest.py
Labels: Please review

#5420 Add coalesce to committee_name in ts_vector column
  data/migrations/V0273__ofec_filings_all_mv_add_coalesce
  data/migrations/V0274__ofec_reports_presidential_mv_add_coalesce
  data/migrations/V0275__ofec_reports_house_senate_mv_add_coalesce
  data/migrations/V0276__ofec_reports_pac_party_mv_add_coalesce
Labels: Please review

#5422 Add coalesce to ts_vector column used by q_filer
  data/migrations/V0273__ofec_filings_all_mv_add_coalesce.sql
  data/migrations/V0274__ofec_reports_presidential_mv_add_coalesce.sql
  data/migrations/V0275__ofec_reports_house_senate_mv_add_coalesce.sql
  data/migrations/V0276__ofec_reports_pac_party_mv_add_coalesce.sql
Labels: Please review

#5424 Fix coalesce error in ofec_filings_all_mv
  data/migrations/V0277__ofec_filings_all_mv_fix_coalesce.sql
Labels: Please review

#5414 [MERGE WITH GITFLOW] Release/public 20230425
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
  data/migrations/V0270__add_fec_fitem_sched_ab_2023_2024.sql
  data/migrations/V0271__h4_mv_create.sql
  manage.py
  tests/factories.py
  tests/test_itemized.py
  webservices/args.py
  webservices/common/models/itemized.py
  webservices/docs.py
  webservices/flow.py
  webservices/resources/sched_h4.py
  webservices/rest.py
  webservices/schemas.py
  webservices/sorting.py
  webservices/tasks/legal_docs.py
Labels: release-branch

#5425 add deprecation notice for by_office and by_office/by_party endpoints
  webservices/docs.py
Labels: Pipeline: Ready
