Repository fecgov/openFEC, pull requests merged in 2024-02, with the labels that each got.

#5710 Upgrade gitpython
  requirements.txt
Labels: Please review

#5709 Upgrade flyway v10.7.1
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
Labels: Please review

#5707 [MERGE WITH GITFLOW] Release/public 20240206
  data/migrations/V0287__add_candidate_firstlast_name_vw.sql
  data/migrations/V0288__add_parsed_name_ofec_candidate_history_mv.sql
  tests/factories.py
  tests/test_candidates.py
  tests/test_filings.py
  tests/test_sched_f.py
  webservices/args.py
  webservices/common/models/candidates.py
  webservices/common/models/filings.py
  webservices/common/models/itemized.py
  webservices/docs.py
  webservices/resources/filings.py
  webservices/rest.py
  webservices/schemas.py
Labels: release-branch

#5711 migrate deploy to run in circleci
  .circleci/config.yml
Labels: Please review

#5713 add last file and f1 indexes (migration file)
  data/migrations/V0289__last_file_ofec_committee_detail_history_mv.sql
Labels: Please review

#5723 Change conduit_committee_zip to string
  webservices/common/models/itemized.py
Labels: Please review

#5715 add last file date filters to /committees/ endpoint
  tests/test_committees.py
  webservices/args.py
  webservices/docs.py
  webservices/resources/committees.py
Labels: Please review

#5719 Fix flake8, prettier, and eof errors. Add precommit to circleci
  .circleci/config.yml
  .codeclimate.yml
  .github/ISSUE_TEMPLATE/issue-template.md
  .gitignore
  .pre-commit-config.yaml
  CONTRIBUTING.md
  LICENSE.md
  PULL_REQUEST_TEMPLATE.md
  data/crosswalks/README_crosswalks.txt
  data/crosswalks/f3_reports.sql
  data/efile_guide_f3.json
  data/efile_guide_f3p.json
  data/efile_guide_f3x.json
  data/load_base_mur_data.sql
  data/notes.md
  requirements-dev.txt
  requirements.txt
  src/public/index.html
  src/static/css/custom.css
  src/static/css/styles.css
  webservices/common/models/committees.py
  webservices/common/models/costs.py
  webservices/common/models/filings.py
  webservices/common/models/operations_log.py
  webservices/common/views.py
  webservices/legal_docs/show_legal_data.py
  webservices/resources/candidate_aggregates.py
  webservices/resources/candidates.py
  webservices/resources/committees.py
  webservices/resources/totals.py
  webservices/rest.py
  webservices/templates/swagger-ui.html
  webservices/utils.py
Labels: Please review

#5724 [MERGE WITH GITFLOW] Release/public 20240220
  .circleci/config.yml
  .codeclimate.yml
  .github/ISSUE_TEMPLATE/issue-template.md
  .gitignore
  .pre-commit-config.yaml
  CONTRIBUTING.md
  LICENSE.md
  PULL_REQUEST_TEMPLATE.md
  README.md
  data/crosswalks/README_crosswalks.txt
  data/crosswalks/f3_reports.sql
  data/efile_guide_f3.json
  data/efile_guide_f3p.json
  data/efile_guide_f3x.json
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
  data/load_base_mur_data.sql
  data/migrations/V0289__last_file_ofec_committee_detail_history_mv.sql
  data/notes.md
  requirements-dev.txt
  requirements.txt
  src/public/index.html
  src/static/css/custom.css
  src/static/css/styles.css
  tests/test_committees.py
  webservices/args.py
  webservices/common/models/committees.py
  webservices/common/models/costs.py
  webservices/common/models/filings.py
  webservices/common/models/itemized.py
  webservices/common/models/operations_log.py
  webservices/common/views.py
  webservices/docs.py
  webservices/legal_docs/show_legal_data.py
  webservices/resources/candidate_aggregates.py
  webservices/resources/candidates.py
  webservices/resources/committees.py
  webservices/resources/totals.py
  webservices/rest.py
  webservices/templates/swagger-ui.html
  webservices/utils.py
Labels: Please review, release-branch
