Repository fecgov/openFEC, pull requests merged in 2024-04, with the labels that each got.

#5781 upgrade flyway 10.10
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
Labels: Please review

#5769 5755-add check and clear queries commands
  cli.py
  manage.py
Labels: Please review, Pipeline: Ready

#5778 Add New Creds Service
  manifests/manifest_api_dev.yml
  manifests/manifest_api_feature.yml
  manifests/manifest_api_prod.yml
  manifests/manifest_api_stage.yml
  manifests/manifest_celery_beat_dev.yml
  manifests/manifest_celery_beat_feature.yml
  manifests/manifest_celery_beat_prod.yml
  manifests/manifest_celery_beat_stage.yml
  manifests/manifest_celery_worker_dev.yml
  manifests/manifest_celery_worker_feature.yml
  manifests/manifest_celery_worker_prod.yml
  manifests/manifest_celery_worker_stage.yml
  manifests/manifest_task_dev.yml.template
  manifests/manifest_task_feature.yml.template
  manifests/manifest_task_prod.yml.template
  manifests/manifest_task_stage.yml.template
Labels: Please review

#5777 Feature/5706 add form 1 efile endpoint
  tests/factories.py
  tests/test_filings.py
  webservices/args.py
  webservices/common/models/filings.py
  webservices/exceptions.py
  webservices/resources/filings.py
  webservices/rest.py
  webservices/schemas.py
Labels: Please review

#5789 5754-add robots.txt
  webservices/rest.py
  webservices/static/robots.txt
Labels: Please review

#5792 revert queries commands
  cli.py
  manage.py
Labels: Please review

#5801 upgrade to 10.11.1
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
Labels: Please review, Before release

#5803 [MERGE WITH GITFLOW] Release/public 20240430
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
  data/migrations/V0292__add_ofec_sched_a_aggregate_employer_mv.sql
  data/migrations/V0293__add_ofec_sched_a_aggregate_occupation_mv.sql
  data/migrations/V0294__recpnt_nm_text_ofec_sched_b_aggregate_recipient_mv.sql
  manage.py
  webservices/flow.py
  webservices/rest.py
  webservices/static/robots.txt
Labels: release-branch
