Repository fecgov/openFEC, pull requests merged in 2024-07, with the labels that each got.

#5883 [MERGE WITH GITFLOW] Release/public 20240702
  tests/test_national_party.py
  webservices/args.py
  webservices/legal_docs/es_management.py
Labels: release-branch

#5893 [MERGE WITH GITFLOW] Release/public 20240717
  README.md
  cli.py
  data/migrations/V0302__add_test_efile_schema_and_table.sql
  tests/test_legal.py
  webservices/args.py
  webservices/legal_docs/__init__.py
  webservices/legal_docs/es_management.py
  webservices/legal_docs/regulations.py
  webservices/legal_docs/responses.py
  webservices/resources/legal.py
Labels: Please review, release-branch

#5899 5807 upgrade flask-cors
  requirements.txt
Labels: Please review

#5894 5845-upgrade requests
  requirements.txt
Labels: Please review

#5861 Add feature flag-dependent test F1 endpoint
  manifests/manifest_api_stage.yml
  webservices/common/models/filings.py
  webservices/docs.py
  webservices/resources/filings.py
  webservices/rest.py
  webservices/schemas.py
Labels: Before release

#5918 Switch analyzer to standard
  webservices/legal_docs/es_management.py
  webservices/resources/legal.py
Labels: Please review

#5912 [MERGE WITH GITFLOW] Release/public 20240730
  manifests/manifest_api_stage.yml
  requirements.txt
  webservices/common/models/filings.py
  webservices/docs.py
  webservices/resources/filings.py
  webservices/rest.py
  webservices/schemas.py
Labels: Please review, release-branch
