Repository fecgov/openFEC, pull requests merged in 2024-10, with the labels that each got.

#5992 [MERGE WITH GITFLOW] Release/public 20241001
  requirements.txt
  tests/integration/test_current_cases.py
  webservices/args.py
  webservices/docs.py
  webservices/legal_docs/advisory_opinions.py
  webservices/legal_docs/current_cases.py
  webservices/legal_docs/es_management.py
  webservices/resources/legal.py
Labels: Please review, release-branch

#5997 5965-add subject filters
  tests/integration/test_current_cases.py
  webservices/args.py
  webservices/docs.py
  webservices/legal_docs/current_cases.py
  webservices/legal_docs/es_management.py
  webservices/resources/legal.py
Labels: Please review

#6004 [MERGE WITH GITFLOW] Hotfix/6003 fix dispositions
  webservices/resources/legal.py
Labels: Please review

#5998 Add doc_type filter to citations
  webservices/args.py
  webservices/docs.py
  webservices/legal_docs/advisory_opinions.py
  webservices/legal_docs/es_management.py
  webservices/resources/legal.py
Labels: Please review

#6010 Upgrade flyway v10.19.0
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
Labels: Please review

#6002 Change citation_text to keyword field
  webservices/legal_docs/es_management.py
Labels: Please review

#6013 Hotfix to add ao_category deprecated filter
  webservices/args.py
  webservices/docs.py
  webservices/resources/legal.py
Labels: Please review

#6008 5982-Fix arch mur and current mur sort
  tests/test_legal.py
  webservices/legal_docs/archived_murs.py
  webservices/legal_docs/current_cases.py
  webservices/resources/legal.py
Labels: Please review

#6014 [MERGE WITH GITFLOW] Release/public 20241015
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
  data/migrations/V0304__add_arch_curent_mur_sorting_vw.sql
  tests/integration/test_current_cases.py
  webservices/args.py
  webservices/docs.py
  webservices/legal_docs/advisory_opinions.py
  webservices/legal_docs/current_cases.py
  webservices/legal_docs/es_management.py
  webservices/resources/legal.py
Labels: Please review

#6015 Filter by document date (AO, AF, ADR and MUR documents)
  webservices/args.py
  webservices/docs.py
  webservices/resources/legal.py
Labels: Please review

#6029 [MERGE WITH GITFLOW] Hotfix/fix election type
  webservices/common/models/costs.py
Labels: Please review, Hotfix

#6025 [MERGE WITH GITFLOW] Release/public 20241029
  tests/integration/test_current_cases.py
  tests/test_legal.py
  webservices/args.py
  webservices/docs.py
  webservices/legal_docs/archived_murs.py
  webservices/legal_docs/current_cases.py
  webservices/resources/legal.py
  webservices/utils.py
Labels: release-branch
