Repository fecgov/openFEC, pull requests merged in 2024-03, with the labels that each got.

#5740 5730-upgrade flyway 10.8.1
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
Labels: Please review

#5743 Change purpose filter from fulltext to multi
  tests/test_aggregates.py
  tests/test_itemized.py
  webservices/args.py
  webservices/resources/aggregates.py
Labels: Please review

#5741 Upgrade python v3.10
  .circleci/config.yml
  README.md
  requirements.txt
  runtime.txt
Labels: Please review

#5748 Remove per_page cap on ScheduleABySizeCandidateView, ScheduleAByStateCandidateView, and ScheduleAByStateCandidateTotalsView
  tests/test_aggregates.py
  webservices/common/views.py
  webservices/resources/candidate_aggregates.py
Labels: Please review, Before release

#5757 [MERGE WITH GITFLOW]Release/public 20240318
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
  requirements.txt
  runtime.txt
  tests/test_aggregates.py
  tests/test_itemized.py
  webservices/args.py
  webservices/common/views.py
  webservices/resources/aggregates.py
  webservices/resources/candidate_aggregates.py
Labels: Please review, release-branch
