Repository fecgov/openFEC, pull requests merged in 2024-09, with the labels that each got.

#5964 5948-remove name & number from should
  webservices/resources/legal.py
Labels: Please review

#5957 [MERGE WITH GITFLOW] Release/public 20240903
  .circleci/config.yml
  README.md
  cli.py
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
  locustfile.py
  manage.py
  package-lock.json
  package.json
  requirements.txt
  webservices/args.py
  webservices/docs.py
  webservices/resources/legal.py
Labels: release-branch

#5977 [MERGE WITH GITFLOW] Release/public 20240917
  data/migrations/V0303__add_disbursement_dt_sched_e.sql
  manage.py
  requirements.txt
  tests/test_aggregates.py
  webservices/common/models/itemized.py
  webservices/common/views.py
  webservices/legal_docs/advisory_opinions.py
  webservices/resources/candidate_aggregates.py
  webservices/resources/legal.py
Labels: release-branch

#5981 remove comment
  requirements.txt
Labels: Please review

#5988 Add Mur disposition category filter
  tests/integration/test_current_cases.py
  webservices/args.py
  webservices/docs.py
  webservices/legal_docs/current_cases.py
  webservices/legal_docs/es_management.py
  webservices/resources/legal.py
Labels: Please review, Work: Back-end

#5991 Fix MUR disposition category list key
  webservices/legal_docs/current_cases.py
Labels: Please review

#5976 5961 add ao_doc_category_id filter
  webservices/args.py
  webservices/docs.py
  webservices/legal_docs/advisory_opinions.py
  webservices/legal_docs/es_management.py
  webservices/resources/legal.py
Labels: Please review
