Repository fecgov/openFEC, pull requests merged in 2024-12, with the labels that each got.

#6063 Release/public 20241126
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
  data/migrations/V0306__update_form_category_ofec_filings_all_mv.sql
  requirements.txt
  tests/common.py
  tests/integration/test_advisory_opinions.py
  tests/integration/test_ao_elasticsearch.py
  tests/integration/test_cases_elasticsearch.py
  tests/integration/test_statute_elasticsearch.py
  tests/test_legal_data.py
  webservices/docs.py
  webservices/legal_docs/advisory_opinions.py
  webservices/resources/legal.py
Labels: release-branch

#6074 add tests for legal/docs and legal/citations endpoints
  tests/common.py
  tests/integration/test_cases_elasticsearch.py
  tests/integration/test_citations_elasticsearch.py
  tests/integration/test_legal_docs_elasticsearch.py
  tests/test_legal_data.py
Labels: Please review

#6082 FIx empty filter bug
  webservices/resources/legal.py
Labels: Please review, Before release

#6079 6078- remove deprecated filter
  tests/integration/test_ao_elasticsearch.py
  webservices/args.py
  webservices/docs.py
  webservices/resources/legal.py
Labels: Please review, Technical debt

#6083 6070-Fix pytest test_efile issue
  tests/conftest.py
Labels: Please review
