Repository fecgov/openFEC, pull requests merged in 2024-05, with the labels that each got.

#5809 Fix sched-a by-employer,by-occupation and schedule_b/by_recipient fulltext and n/a search issue
  tests/test_aggregates.py
  webservices/common/models/aggregates.py
  webservices/common/views.py
  webservices/filters.py
  webservices/resources/aggregates.py
  webservices/schemas.py
Labels: Please review

#5813 upgrade werkzeug v3
  requirements.txt
  webservices/resources/download.py
  webservices/tasks/download.py
Labels: Please review

#5829 upgrade gunicorn v22
  requirements.txt
Labels: Please review

#5825 5808- upgrade flyway 10.12.0
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
Labels: Please review

#5824 Fix N/A fulltext search for schedule a and b
  tests/test_filters.py
  webservices/resources/sched_a.py
  webservices/resources/sched_b.py
Labels: Please review, Before release

#5791 Add national party schedule a/b endpoints
  tests/factories.py
  tests/test_national_party.py
  webservices/args.py
  webservices/common/models/__init__.py
  webservices/common/models/national_party.py
  webservices/docs.py
  webservices/resources/national_party.py
  webservices/rest.py
  webservices/schemas.py
  webservices/spec.py
Labels: Please review

#5833 Add MV for national party aggregate data
  data/migrations/V0297__add_ofec_totals_national_party_mv.sql
  manage.py
  webservices/flow.py
Labels: Please review

#5835 [MERGE WITH GITFLOW]Release/public 20240521
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
  data/migrations/V0295__refactor_ofec_sched_a_nat_party_mv.sql
  data/migrations/V0296__refactor_ofec_sched_b_nat_party_mv.sql
  requirements.txt
  tests/factories.py
  tests/test_aggregates.py
  tests/test_filters.py
  tests/test_national_party.py
  webservices/args.py
  webservices/common/models/__init__.py
  webservices/common/models/aggregates.py
  webservices/common/models/national_party.py
  webservices/common/views.py
  webservices/docs.py
  webservices/filters.py
  webservices/resources/aggregates.py
  webservices/resources/download.py
  webservices/resources/national_party.py
  webservices/resources/sched_a.py
  webservices/resources/sched_b.py
  webservices/rest.py
  webservices/schemas.py
  webservices/spec.py
  webservices/tasks/download.py
Labels: release-branch

#5838 Increase size for inner hits
  locustfile.py
  webservices/resources/legal.py
Labels: Please review

#5846 national party totals endpoint
  tests/factories.py
  tests/test_national_party.py
  webservices/args.py
  webservices/common/models/national_party.py
  webservices/docs.py
  webservices/resources/national_party.py
  webservices/rest.py
  webservices/schemas.py
Labels: Please review

#5826 Add task to create new public api keys
  .gitignore
  cli.py
  manage.py
Labels: Please review
