Repository fecgov/openFEC, pull requests merged in 2025-08, with the labels that each got.

#6274 Add rulemaking endpoint to swagger UI
  tests/common.py
  tests/test_legal/test_case_endpoint.py
  tests/test_legal/test_legal_data.py
  tests/test_legal/test_rm_endpoint.py
  webservices/api_setup.py
  webservices/args.py
  webservices/constants.py
  webservices/docs.py
  webservices/resources/rulemaking.py
  webservices/rest.py
  webservices/rulemaking_docs/responses.py
  webservices/rulemaking_docs/rm_mapping.py
  webservices/utils.py
Labels: Please review, Work: Back-end

#6313 [MERGE WITH GITFLOW] Release/public 20250812
  data/migrations/V0313__add_contents_column.sql
  requirements.txt
  tests/common.py
  tests/test_legal/test_case_endpoint.py
  tests/test_legal/test_legal_data.py
  tests/test_legal/test_rm_endpoint.py
  tests/test_swagger.py
  webservices/api_setup.py
  webservices/args.py
  webservices/constants.py
  webservices/docs.py
  webservices/resources/dates.py
  webservices/resources/download.py
  webservices/resources/rulemaking.py
  webservices/rest.py
  webservices/rulemaking_docs/responses.py
  webservices/rulemaking_docs/rm_mapping.py
  webservices/schemas.py
  webservices/utils.py
Labels: Please review, release-branch

#6326 6325- fix filename search
  webservices/legal_docs/es_management.py
  webservices/resources/legal.py
Labels: Please review

#6327 Refactor legal code
  cli.py
  tests/common.py
  tests/test_legal/test_ao_citations.py
  tests/test_legal/test_ao_endpoint.py
  tests/test_legal/test_ao_load.py
  tests/test_legal/test_case_endpoint.py
  tests/test_legal/test_case_load.py
  tests/test_legal/test_citation_endpoint.py
  tests/test_legal/test_legal.py
  tests/test_legal/test_legal_doc_endpoint.py
  tests/test_legal/test_map_citations_murs.py
  tests/test_legal/test_parse_mur_citations.py
  tests/test_legal/test_rm_endpoint.py
  tests/test_legal/test_rm_load.py
  tests/test_legal/test_statute_endpoint.py
  webservices/legal/constants.py
  webservices/legal/legal_docs/__init__.py
  webservices/legal/legal_docs/advisory_opinions.py
  webservices/legal/legal_docs/archived_murs.py
  webservices/legal/legal_docs/current_cases.py
  webservices/legal/legal_docs/reclassify_statutory_citation.py
  webservices/legal/legal_docs/responses.py
  webservices/legal/legal_docs/show_legal_data.py
  webservices/legal/legal_docs/statutes.py
  webservices/legal/mappings/ao_mapping.py
  webservices/legal/mappings/arch_mur_mapping.py
  webservices/legal/mappings/case_mapping.py
  webservices/legal/mappings/rm_mapping.py
  webservices/legal/rulemaking_docs/__init__.py
  webservices/legal/rulemaking_docs/responses.py
  webservices/legal/rulemaking_docs/rulemaking.py
  webservices/legal/utils_es.py
  webservices/legal/utils_load.py
  webservices/resources/legal.py
  webservices/resources/rulemaking.py
  webservices/tasks/download.py
  webservices/tasks/legal_docs.py
  webservices/utils.py
  webservices/utils_es.py
Labels: Please review

#6332 [MERGE WITH GITFLOW] Release/public 20250826
  cli.py
  tests/common.py
  tests/conftest.py
  tests/test_legal/test_ao_citations.py
  tests/test_legal/test_ao_endpoint.py
  tests/test_legal/test_ao_load.py
  tests/test_legal/test_case_endpoint.py
  tests/test_legal/test_case_load.py
  tests/test_legal/test_citation_endpoint.py
  tests/test_legal/test_legal.py
  tests/test_legal/test_legal_doc_endpoint.py
  tests/test_legal/test_map_citations_murs.py
  tests/test_legal/test_parse_mur_citations.py
  tests/test_legal/test_rm_endpoint.py
  tests/test_legal/test_rm_load.py
  tests/test_legal/test_statute_endpoint.py
  webservices/args.py
  webservices/common/models/itemized.py
  webservices/common/models/reports.py
  webservices/common/models/totals.py
  webservices/docs.py
  webservices/legal/constants.py
  webservices/legal/legal_docs/__init__.py
  webservices/legal/legal_docs/advisory_opinions.py
  webservices/legal/legal_docs/archived_murs.py
  webservices/legal/legal_docs/current_cases.py
  webservices/legal/legal_docs/reclassify_statutory_citation.py
  webservices/legal/legal_docs/responses.py
  webservices/legal/legal_docs/show_legal_data.py
  webservices/legal/legal_docs/statutes.py
  webservices/legal/mappings/ao_mapping.py
  webservices/legal/mappings/arch_mur_mapping.py
  webservices/legal/mappings/case_mapping.py
  webservices/legal/mappings/rm_mapping.py
  webservices/legal/rulemaking_docs/__init__.py
  webservices/legal/rulemaking_docs/responses.py
  webservices/legal/rulemaking_docs/rulemaking.py
  webservices/legal/utils_es.py
  webservices/legal/utils_load.py
  webservices/resources/legal.py
  webservices/resources/rulemaking.py
  webservices/tasks/download.py
  webservices/tasks/legal_docs.py
  webservices/utils.py
  webservices/utils_es.py
Labels: Please review, release-branch
