Repository fecgov/openFEC, pull requests merged in 2025-06, with the labels that each got.

#6242 [MERGE WITH GITFLOW] Hotfix/fix candidate committee download
  webservices/common/counts.py
  webservices/resources/candidates.py
  webservices/resources/committees.py
  webservices/resources/reports.py
  webservices/resources/totals.py
  webservices/tasks/download.py
Labels: Hotfix

#6264 6256-upgrade requests
  requirements.txt
Labels: Please review, Security: general

#6269 Add migration file for fosers
  data/migrations/V0311__add_fosers_tables.sql
Labels: Please review

#6259 Upgrade sqlalchemy v2.0
  manage.py
  requirements.txt
  tests/common.py
  tests/conftest.py
  tests/integration/test_amendment_chain.py
  tests/integration/test_candidate_committee_totals.py
  tests/integration/test_candidates.py
  tests/integration/test_committees.py
  tests/integration/test_filings.py
  tests/integration/test_followers.py
  tests/integration/test_integration.py
  tests/integration/test_tsvector_generation.py
  tests/test_app.py
  tests/test_legal/test_ao_citations.py
  tests/test_legal/test_ao_endpoint.py
  tests/test_legal/test_ao_load.py
  tests/test_legal/test_case_endpoint.py
  tests/test_legal/test_case_load.py
  tests/test_legal/test_citation_endpoint.py
  tests/test_legal/test_legal.py
  tests/test_legal/test_legal_data.py
  tests/test_legal/test_legal_doc_endpoint.py
  tests/test_legal/test_map_citations_murs.py
  tests/test_legal/test_parse_mur_citations.py
  tests/test_legal/test_rm_load.py
  tests/test_legal/test_statute_endpoint.py
  webservices/filters.py
  webservices/legal_docs/advisory_opinions.py
  webservices/legal_docs/archived_murs.py
  webservices/legal_docs/current_cases.py
  webservices/resources/audit.py
  webservices/resources/candidate_aggregates.py
  webservices/resources/elections.py
  webservices/resources/search.py
  webservices/rulemaking_docs/rulemaking.py
  webservices/sorting.py
  webservices/tasks/legal_docs.py
  webservices/utils.py
Labels: Please review
