Repository fecgov/openFEC, pull requests merged in 2025-04, with the labels that each got.

#6173 add functionality to sort advisory opinions by issue_date
  tests/integration/test_ao_elasticsearch.py
  webservices/resources/legal.py
Labels: Please review

#6189 upgrade flyway v11.6
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
Labels: Please review

#6187 6176- upgrade gunicorn to v.23.0.0
  requirements.txt
Labels: Please review

#6182 Add proximity_preserve_order filter
  tests/integration/test_ao_elasticsearch.py
  tests/integration/test_cases_elasticsearch.py
  webservices/args.py
  webservices/docs.py
  webservices/resources/legal.py
Labels: Please review, Before release

#6190 [MERGE WITH GITFLOW] Release/public 20250415
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
  requirements.txt
  tests/integration/test_ao_elasticsearch.py
  tests/integration/test_cases_elasticsearch.py
  webservices/args.py
  webservices/docs.py
  webservices/resources/legal.py
Labels: Please review, release-branch

#6197 Upgrade postgres in circleci pipeline
  .circleci/config.yml
Labels: Please review

#6204 6179-add legal/docs to swagger
  tests/test_swagger.py
  webservices/docs.py
  webservices/legal_docs/responses.py
  webservices/resources/legal.py
  webservices/rest.py
Labels: Please review

#6205 [MERGE WITH GITFLOW] Release/public 20250429
  .circleci/config.yml
  cli.py
  manage.py
  webservices/docs.py
  webservices/resources/legal.py
Labels: release-branch

#6199 Create task and endpoint to monitor celery
  tests/test_monitoring.py
  webservices/api_setup.py
  webservices/resources/monitoring.py
  webservices/rest.py
  webservices/tasks/__init__.py
  webservices/tasks/celery.py
  webservices/tasks/service_status_checks.py
  webservices/tasks/utils.py
Labels: Please review
