Repository fecgov/openFEC, pull requests merged in 2025-02, with the labels that each got.

#6114 upgrade cf cli
  .circleci/config.yml
Labels: Please review

#6120 Combine nested queries
  tests/test_legal.py
  webservices/resources/legal.py
Labels: Please review

#6128 Change before and after filters in legal proximity search
  tests/integration/test_ao_elasticsearch.py
  tests/integration/test_cases_elasticsearch.py
  webservices/resources/legal.py
Labels: Please review, Before release

#6130 Allow zero input from integer filters in legal search
  webservices/resources/legal.py
Labels: Please review

#6129 60847-Add parsed candidate name to candidate detail
  data/migrations/V0308__add_parsed_name_candidate_detail_mv.sql
  webservices/common/models/candidates.py
Labels: Please review

#6122 [MERGE WITH GITFLOW] Release/public 20250211
  .circleci/config.yml
  data/migrations/V0307__add_fec_fitem_sched_ab_2025_2026.sql
  tests/integration/test_ao_elasticsearch.py
  tests/integration/test_cases_elasticsearch.py
  tests/test_legal.py
  webservices/common/models/large_aggregates.py
  webservices/docs.py
  webservices/resources/legal.py
  webservices/schemas.py
Labels: release-branch

#6132 Add test candidate parsed name
  tests/test_candidates.py
  webservices/common/models/candidates.py
Labels: Please review

#6136 upgrade flyway
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
Labels: Please review, Before release

#6137 fix q_exclude for statutes
  webservices/resources/legal.py
Labels: Before release

#6144 upgrade flyway to V11.3.3
  .circleci/config.yml
  README.md
  data/flyway/build.gradle
  data/flyway/manifest_headless_flyway.yml
Labels: Please review

#6149 6131 switch q_exclude to SQS
  webservices/resources/legal.py
Labels: Please review
